version: "3"

services:
  funds_stocks:
    container_name: funds_stocks
    restart: always
    volumes:
      - /data/app/logs/py-tools:/py-tools/app/logs
      - /etc/localtime:/etc/localtime
      - /data/app/pywebio-funds:/py-tools
    build:
      context: ""
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "80:8080"