version: "3"

services:
  py-tools:
    container_name: py-tools
    restart: always
    volumes:
      - /data/app/logs/py-tools:/py-tools/app/logs
      - /etc/localtime:/etc/localtime
    build:
      context: ""
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "80:8080"